services:
  astro:
    build: .
    # container_name: astro-dev
    working_dir: /app
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: development
    ports:
      - "4321:4321"
    tty: true
    stdin_open: true
    command: npx astro dev --host 0.0.0.0 --port 4321
